const catalogo = [
  [
    "organizacao-escolar",
    "Escola",
    "Organizar meus estudos",
    "Organizar meus estudos e entregar as atividades no prazo.",
    "Listar as atividades pendentes.",
    "Revisar duas matérias por semana.",
    "Registrar quatro revisões e conferir as entregas.",
    "Usar duas sessões semanais de 30 minutos.",
    "Acompanhar melhor as aulas e reduzir acúmulos.",
    "Testar por quatro semanas e revisar os resultados.",
  ],
  [
    "matematica",
    "Escola",
    "Melhorar em matemática",
    "Entender um conteúdo de matemática em que tenho dificuldade.",
    "Escolher um conteúdo e tentar três exercícios.",
    "Aprender a resolver problemas de porcentagem.",
    "Resolver dez questões e explicar minhas respostas.",
    "Praticar duas vezes por semana e pedir ajuda quando necessário.",
    "Usar porcentagem na escola e no dia a dia.",
    "Concluir a lista em quatro semanas.",
  ],
  [
    "comunicacao",
    "Trabalho",
    "Melhorar minha comunicação",
    "Comunicar minhas ideias com clareza no trabalho.",
    "Preparar uma explicação de dois minutos.",
    "Apresentar uma atividade com começo, meio e fim.",
    "Fazer três apresentações curtas e pedir feedback.",
    "Praticar duas vezes por semana com alguém de confiança.",
    "Participar das conversas com mais segurança.",
    "Realizar três apresentações em quatro semanas.",
  ],
  [
    "organizacao-trabalho",
    "Trabalho",
    "Organizar minhas tarefas",
    "Organizar tarefas de trabalho e acompanhar seus prazos.",
    "Anotar as tarefas e confirmar prioridades com meu responsável.",
    "Usar uma lista diária de tarefas e prioridades.",
    "Registrar dez dias e conferir as conclusões.",
    "Reservar cinco minutos no começo e no fim do expediente, com orientação.",
    "Reduzir esquecimentos e entender as prioridades.",
    "Testar a lista por duas semanas.",
  ],
  [
    "excel",
    "Tecnologia",
    "Aprender Excel ou Planilhas Google",
    "Aprender a criar planilhas para organizar informações.",
    "Criar uma tabela com títulos e dados.",
    "Aprender soma, média e organização de tabelas.",
    "Criar dez registros e duas fórmulas funcionando.",
    "Usar materiais gratuitos em duas sessões semanais.",
    "Aplicar planilhas em atividades pessoais e profissionais.",
    "Concluir a planilha em quatro semanas.",
  ],
  [
    "programacao",
    "Tecnologia",
    "Começar a programar",
    "Aprender programação criando um pequeno projeto.",
    "Executar meu primeiro exemplo numa ferramenta acessível.",
    "Aprender variáveis, condições e repetições.",
    "Resolver seis exercícios e criar um programa simples.",
    "Usar uma ferramenta gratuita compatível com meu aparelho.",
    "Conhecer programação e avaliar meu interesse pela área.",
    "Concluir exercícios e projeto em oito semanas.",
  ],
  [
    "ingles",
    "Idiomas",
    "Praticar inglês",
    "Aprender e usar expressões básicas de inglês.",
    "Escolher cinco expressões úteis.",
    "Apresentar-me e falar sobre minha rotina em inglês.",
    "Escrever cinco frases e gravar uma apresentação curta.",
    "Praticar por 15 minutos com materiais adequados ao meu nível.",
    "Ampliar minhas possibilidades de comunicação.",
    "Preparar a apresentação em quatro semanas.",
  ],
  [
    "financas",
    "Vida pessoal",
    "Organizar meu dinheiro",
    "Entender receitas e despesas para organizar meu dinheiro.",
    "Anotar os ganhos e gastos de um dia.",
    "Registrar receitas e despesas por categoria.",
    "Conferir os totais semanais por quatro semanas.",
    "Usar caderno ou aplicativo por cinco minutos ao dia.",
    "Planejar melhor minhas escolhas.",
    "Analisar os registros após quatro semanas.",
  ],
  [
    "leitura",
    "Vida pessoal",
    "Criar uma rotina de leitura",
    "Ler com mais frequência e compreender melhor os textos.",
    "Escolher um texto e ler por dez minutos.",
    "Ler textos de um tema de meu interesse.",
    "Registrar uma ideia principal por sessão.",
    "Começar com dez minutos e materiais disponíveis.",
    "Ampliar meu repertório e compreensão.",
    "Manter o registro por quatro semanas.",
  ],
];
export const metas = catalogo.map(
  ([id, categoria, titulo, descricao, primeiroPasso, S, M, A, R, T]) => ({
    id,
    categoria,
    titulo,
    descricao,
    primeiroPasso,
    exemplosSmart: { S, M, A, R, T },
  }),
);
export const categoriasMetas = [...new Set(metas.map((m) => m.categoria))];
export const buscarMeta = (id) => metas.find((m) => m.id === id);
